name: ml-benchmark
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudf=24.08
  - cuml=24.08
  - scikit-learn
  - pandas
  - matplotlib
  - pip
  - ca-certificates
  - conda-forge::codecarbon
  - pip:
    - xgboost==2.0.0

